name: GitHub Pages

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - uses: cargo-bins/cargo-binstall@main
      - uses: Swatinem/rust-cache@v1

      - name: Setup Node
        uses: actions/setup-node@v3.8.1

      - name: NPM install
        run: npm install -D tailwindcss

      - name: Install Dioxus CLI
        run: cargo binstall --no-confirm dioxus-cli --force

      - name: Install mdbook CLI
        run: cargo binstall --no-confirm mdbook --locked --force

      - name: Make build script executable
        run: chmod +x ./build.sh

      - name: Run build script
        run: ./build.sh

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: dist
          target-folder: .
